### ISSUE TITLE
Firedragon

### ISSUE THREAD

**Issue by rachid** [bubblebox/server#10]
Besides the issues marked as features. I think we need some basic design of the app like 'user can do ...' focusing on a happy path. Because I am missing the base line of firedragon, where should we start. 

Should we have a look at the current firefly implementation?

**Comment by ariejan** [comment]
Good point. I'll pick this up so everyone can get an better picture of my idea and pitch in their own.

**Comment by rachid** [comment]
Great :+1:

**Comment by ariejan** [comment]
I started writing things down at the wiki: https://github.com/ariejan/firedragon/wiki/Features-and-User-Stories. Please feel free to contribute or ask questions.
