### ISSUE TITLE
Split project and move to Github organization

### ISSUE THREAD

**Issue by ariejan** [bubblebox/server#37]
Over time I've started to doubt if it's wise to have both the golang server _and_ the Ember.js dashboard in the same repository. 

How do you feel about splitting Fire Dragon (possibly renamed) into two separate projects under a Github organization. IMHO this would:
1. make project setup, testing/ci, etc. easier
2. make attracting developers for specific technologies easier
3. allow for better branding
4. allow for more related projects (OS X Client, example projects, etc.)

Please respond with a :+1: or :-1: to cast your vote.

/cc @bazzel @RoelN @mirrorspock @rachid @Tuxified @eirvandelden

**Comment by Tuxified** [comment]
Sounds :+1: if you plan to have different versions of server / client (Ember vs. React vs Elm or Go vs. Elixir). If you plan to keep it this way, than it's nicer to have it as one package. 

I also wonder if you plan to split up website, API & admin apart, but that's another discussion :)

**Comment by bazzel** [comment]
Currently the Ember app (although it _is_ Ember) is just a client. So splitting up, sounds good to me, it amy also make the commits clearer? 

:+1:

**Comment by ariejan** [comment]
@Tuxified I do _not_ plan on having different implementations, but I _do_ plan on having multiple clients. For instance, when image hosting is added, you'd need to go to the Ember.js dashboard, add your image and upload it. I can imagine a future where someone creates an OS X client that sits in the menu bar and uploads an image you drag to it, copying the short URL to your clipboard. 

Splitting the website/api/admin would be part of this. Serving content and the API are still the server's responsibility. The 'admin' part would just be an Ember app. There would be some documentation or ideally Docker images, to set things up properly.

@bazzel I agree that commits and discussions will be clearer - as well as CI feedback, etc.

**Comment by RoelN** [comment]
[image: :+1:]

On Fri, Dec 11, 2015 at 11:22 AM, Ariejan de Vroom <notifications@github.com

**Comment by eirvandelden** [comment]
:+1:

**Comment by rachid** [comment]
:+1: Especiall no. 4, I am used having client / server in seperate repo's because ember-cli tends to have its own set of of gitignore and project settings etc.

**Comment by ariejan** [comment]
@rachid that, but I'm also thinking of writing a CLI client (in Golang) and maybe an OS X client for easily sharing stuff.

**Comment by ariejan** [comment]
Everything has been moved over to https://github.com/bubblebox:
- Server: https://github.com/bubblebox/server
- Ember client: https://github.com/bubblebox/client-ember

Open pull requests have been closed - but branches are available on `server` for a while. Please open new PR's on `client-ember`.

Both projects have Travis setup.

If you can't access something - give me a holler!
